spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/postgres
    username: user
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis-service
      port: 6379

  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest

  cache:
    type: redis

server:
  port: 8080

logging:
  level:
    org.springframework: INFO